#!/usr/bin/python3
import sys

def factorize(n):
    for i in range(2, n):
        if n % i == 0:
            return i, n // i
    return None, None

def main(filename):
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        p, q = factorize(n)
        if p is not None and q is not None:
            print(f"{n}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        filename = sys.argv[1]
        main(filename)

