#!/usr/bin/env bash

_factorize()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                c=0
                n2=1
                for a in ${args[*]};
                do
                        if [ $c -gt 1 ];
                        then
                                n2=$(echo $a*$n2 | bc)
                        fi
                        c=$((c + 1))
                done
        else
                n2=$3
        fi

        n1=$2
        n=$(echo "$1" | tr ':' '=')

        res=$(echo "if($n2 > $n1) 1 else 0" | bc)
	        if ((res == 1)); then
		        np=$n1
		        n1=$n2
		        n2=$np
                fi

        echo "$n$n1*$n2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                res=$(factor "$i")
                _factorize $res

        done < "$1"
fi
